SELECT
Transaction_ID,
Issued_Document_ID,
Issued_Document_Details_ID,
Issued_Date,
Transactor_ID,
Transactor_Description,
Transactor_Type_Desription,
Debit,
Credit,
Issuable_Document_Description,
Document_Official_Number_Sequence,
Intention_ID,
Intention_Description,
Is_Positive,
Sector
FROM FinalDebitAndCreditForFinancialTransactorFromProductDetailsQ

UNION

SELECT
Transaction_ID,
Issued_Document_ID,
Issued_Document_Details_ID,
Issued_Date,
Transactor_ID,
Transactor_Description,
Transactor_Type_Desription,
Debit,
Credit,
Issuable_Document_Description,
Document_Official_Number_Sequence,
Intention_ID,
Intention_Description,
Is_Positive,
Sector
FROM FinalDebitAndCreditForFinancialTransactorsFromFinancialDetailsQ

UNION

SELECT
Transaction_ID,
Issued_Document_ID,
Issued_Document_Details_ID,
Issued_Date,
Transactor_ID,
Transactor_Description,
Transactor_Type_Desription,
Debit,
Credit,
Issuable_Document_Description,
Document_Official_Number_Sequence,
Intention_ID,
Intention_Description,
Is_Positive,
Sector
FROM FinalDebitAndCreditForProDocumentOtherEntityFinancialTransactorQ

UNION SELECT
Transaction_ID,
Issued_Document_ID,
Issued_Document_Details_ID,
Issued_Date,
Transactor_ID,
Transactor_Description,
Transactor_Type_Desription,
Debit,
Credit,
Issuable_Document_Description,
Document_Official_Number_Sequence,
Intention_ID,
Intention_Description,
Is_Positive,
Sector
FROM FinalDebitAndCreditForVatTransactorsFromProductDetailsQ;

